#ifndef PPG_COMPRESS_STAT7_H_
#define PPG_COMPRESS_STAT7_H_

#ifdef __cplusplus
extern "C" {
#endif

// Auto-generated by gen_compression_c.py — DO NOT EDIT BY HAND.
// Compresses 25 raw IR sub-samples per 0.5s frame into
// 7 statistical features: [mean, std, min, max, rms, skew, kurtosis]
// then appends 3 passthrough channels (spo2, bpm, motion_level)
// to form one output row of 10 channels per frame.
//
// Input window layout expected: (60, 28)
//   columns: [spo2, bpm, ir_0..ir_24, motion_level]
// Output window layout produced: (60, 10)
//   columns: [mean, std, min, max, rms, skew, kurtosis, spo2, bpm, motion_level]

#define PPG_COMPRESS_STAT7_WINDOW_FRAMES   60
#define PPG_COMPRESS_STAT7_FRAME_SAMPLES   25
#define PPG_COMPRESS_STAT7_N_COMPRESSED    7
#define PPG_COMPRESS_STAT7_N_PASSTHROUGH   3
#define PPG_COMPRESS_STAT7_N_OUT_CHANNELS  10

// Compresses a single frame's 25 raw IR samples into
// 7 feature values, written to out[0..6].
void ppg_compress_stat7_compress_frame(const float *ir_samples, int n_samples, float *out);

// Processes one full window of raw input rows (each row:
// [spo2, bpm, ir_0..ir_24, motion_level]) into
// 60 output rows of 10 channels each.
// in_window:  flat array, 60 * 28 floats, row-major
// out_window: flat array, 60 * 10 floats, row-major (caller-allocated)
void ppg_compress_stat7_compress_window(const float *in_window, float *out_window);

#ifdef __cplusplus
}
#endif

#endif // PPG_COMPRESS_STAT7_H_
