/**
 * @file ble_notification_manager.cpp
 * @brief Hiá»‡n thá»±c Há»‡ thá»‘ng Truyá»n tin BLE Äa hÃ nh Ä‘á»™ng (Multi-Action Notification)
 */

#include "ble_notification_manager.h"
#include <stdio.h>
#include <string.h>

#if __has_include("gatt_db.h")
#include "gatt_db.h"
#include "sl_bt_api.h"
#include "sl_status.h"
#endif

// Robust handle aliases for autogenerated gatt_db.h names
#if defined(gattdb_gattdb_wearable_data) && !defined(gattdb_wearable_data)
#define gattdb_wearable_data gattdb_gattdb_wearable_data
#elif !defined(gattdb_wearable_data)
#define gattdb_wearable_data 27
#endif

#if defined(gattdb_gattdb_health_telemetry) && !defined(gattdb_health_telemetry)
#define gattdb_health_telemetry gattdb_gattdb_health_telemetry
#elif !defined(gattdb_health_telemetry)
#define gattdb_health_telemetry 30
#endif

#if defined(gattdb_gattdb_system_control) && !defined(gattdb_system_control)
#define gattdb_system_control gattdb_gattdb_system_control
#elif !defined(gattdb_system_control)
#define gattdb_system_control 33
#endif

static uint8_t active_connection_handle = 0xFF;
static bool app_is_subscribed = false;
static uint16_t global_seq_num = 0;

void somniguard_ble_manager_init(void)
{
    active_connection_handle = 0xFF;
    app_is_subscribed = false;
    global_seq_num = 0;
    // printf("[BLE MGR] SomniGuard BLE Notification Manager Initialized.\r\n");
}

void somniguard_ble_set_subscribed(uint8_t connection_handle, bool is_subscribed)
{
    active_connection_handle = connection_handle;
    app_is_subscribed = is_subscribed;
    // printf("[BLE MGR] Connection 0x%02X Subscription Status: %s\r\n",
    //        connection_handle, is_subscribed ? "SUBSCRIBED" : "UNSUBSCRIBED");
}

bool somniguard_ble_is_subscribed(void)
{
    return app_is_subscribed;
}

void somniguard_ble_log_packet(const somniguard_ble_event_pkt_t *pkt)
{
    // printf("[BLE NOTIFY] Sent Pkt -> Type: 0x%02X, Code: 0x%02X, Seq: %u, Param1: %u, Param2: %u\r\n",
    //        pkt->event_type, pkt->event_code, pkt->seq_num, pkt->param1, pkt->param2);
}

bool somniguard_ble_send_sos_msg(void)
{
#if defined(gattdb_wearable_data)
    const char sos_str[] = "SOS";
   // printf("[BLE MGR] Sending SOS Emergency Notification Payload ('SOS')...\r\n");

    if (active_connection_handle != 0xFF && app_is_subscribed)
    {
        sl_status_t sc = sl_bt_gatt_server_send_notification(
            active_connection_handle,
            gattdb_wearable_data,
            sizeof(sos_str) - 1,
            (const uint8_t *)sos_str);
        return (sc == SL_STATUS_OK);
    }
    else
    {
        sl_status_t sc = sl_bt_gatt_server_notify_all(
            gattdb_wearable_data,
            sizeof(sos_str) - 1,
            (const uint8_t *)sos_str);
        return (sc == SL_STATUS_OK);
    }
#else
    return true;
#endif
}

bool somniguard_ble_notify_event(somniguard_ble_evt_type_t type,
                                 somniguard_ble_evt_code_t code,
                                 uint16_t param1,
                                 uint16_t param2)
{
    somniguard_ble_event_pkt_t pkt;
    pkt.event_type = (uint8_t)type;
    pkt.event_code = (uint8_t)code;
    pkt.seq_num = ++global_seq_num;
    pkt.param1 = param1;
    pkt.param2 = param2;

    // Log ra UART console
    somniguard_ble_log_packet(&pkt);

    // Náº¿u lÃ  cáº£nh bÃ¡o sá»©c khá»e / ngÆ°ng thá»Ÿ kháº©n cáº¥p, gá»­i thÃªm chuá»—i "SOS" Ä‘á»ƒ Android App báº¯t Ä‘Æ°á»£c ngay láº­p tá»©c
    if (type == SOMNIGUARD_BLE_EVT_TYPE_HEALTH_ALERT || code == SOMNIGUARD_BLE_EVT_CODE_APNEA_WARNING)
    {
        somniguard_ble_send_sos_msg();
    }

#if defined(gattdb_wearable_data)
    if (active_connection_handle != 0xFF && app_is_subscribed)
    {
        sl_status_t sc = sl_bt_gatt_server_send_notification(
            active_connection_handle,
            gattdb_wearable_data,
            sizeof(somniguard_ble_event_pkt_t),
            (const uint8_t *)&pkt);

        if (sc == SL_STATUS_OK)
        {
            return true;
        }
        else
        {
          //  printf("[BLE MGR] WARNING: Send notification failed (sc=0x%04X)\r\n", (unsigned int)sc);
            return false;
        }
    }
    else
    {
        sl_status_t sc = sl_bt_gatt_server_notify_all(
            gattdb_wearable_data,
            sizeof(somniguard_ble_event_pkt_t),
            (const uint8_t *)&pkt);
        return (sc == SL_STATUS_OK);
    }
#else
    return true;
#endif
}

bool somniguard_ble_notify_telemetry(const somniguard_ble_telemetry_pkt_t *telemetry)
{
    if (telemetry == NULL)
    {
        return false;
    }

    // Format string payload for Android App UI consumption: "SpO2:96.5% BPM:75" or "NO FINGER"
    char telem_str[32];
    bool is_finger_on = (telemetry->posture_flags & (1 << 3)) != 0;
    if (is_finger_on)
    {
        snprintf(telem_str, sizeof(telem_str), "SpO2:%.1f%% BPM:%.0f",
                 (float)telemetry->spo2_x100 / 100.0f,
                 (float)telemetry->hr_x10 / 10.0f);
    }
    else
    {
        snprintf(telem_str, sizeof(telem_str), "NO FINGER");
    }

  //  printf("[BLE TELEM #%u] Dispatched '%s' over BLE RF (conn=0x%02X)\r\n",
        //   telemetry->seq_num, telem_str, active_connection_handle);

#if defined(gattdb_wearable_data)
    // Gá»­i chuá»—i telemetry lÃªn Characteristic 0000FFE1-0000-1000-8000-00805F9B34FB (Android App Ä‘ang láº¯ng nghe)
    if (active_connection_handle != 0xFF)
    {
        sl_bt_gatt_server_send_notification(
            active_connection_handle,
            gattdb_wearable_data,
            strlen(telem_str),
            (const uint8_t *)telem_str);
    }
    else
    {
        sl_bt_gatt_server_notify_all(
            gattdb_wearable_data,
            strlen(telem_str),
            (const uint8_t *)telem_str);
    }
#endif

#if defined(gattdb_gattdb_health_telemetry)
    if (active_connection_handle != 0xFF)
    {
        sl_bt_gatt_server_send_notification(
            active_connection_handle,
            gattdb_gattdb_health_telemetry,
            sizeof(somniguard_ble_telemetry_pkt_t),
            (const uint8_t *)telemetry);
    }
    else
    {
        sl_bt_gatt_server_notify_all(
            gattdb_gattdb_health_telemetry,
            sizeof(somniguard_ble_telemetry_pkt_t),
            (const uint8_t *)telemetry);
    }
#endif
    return true;
}

void somniguard_ble_handle_downlink_cmd(const uint8_t *data, uint16_t len, void *fsm_ptr)
{
    (void)fsm_ptr;
    if (data == NULL || len == 0)
    {
        return;
    }

    uint8_t cmd_id = data[0];
    uint8_t param1 = (len > 1) ? data[1] : 0;
   // printf("[BLE DOWNLINK] Received Command ID: 0x%02X, Param1: 0x%02X (Len: %u)\r\n",
        //   cmd_id, param1, len);

    switch (cmd_id)
    {
    case 0x01: // Mute Alarm / Silence Buzzer & Haptics
       // printf("[BLE DOWNLINK] Command 0x01: Muting active alarm!\r\n");
        // Silence active alarms via FSM if available
        break;

    case 0x02: // Manual Spot-Check
      //  printf("[BLE DOWNLINK] Command 0x02: Triggering manual spot-check...\r\n");
        break;

    case 0x03: // Force Graceful EM4 Shutdown
      //  printf("[BLE DOWNLINK] Command 0x03: Force Enter EM4 Graceful Shutoff!\r\n");
        break;

    case 0x04: // Set Sensitivity Level
       // printf("[BLE DOWNLINK] Command 0x04: Set Apnea Sensitivity Level to %u\r\n", param1);
        break;

    case 0x05: // Sync System Timestamp
      //  printf("[BLE DOWNLINK] Command 0x05: Sync Timestamp\r\n");
        break;

    default:
      //  printf("[BLE DOWNLINK WARN] Unknown Command ID: 0x%02X\r\n", cmd_id);
        break;
    }
}
