name: 04-TruffleHog-Security-Scan
on:
  push:
    branches:
      - main
      - master
      - develop
      - "release/**"
jobs:
  trufflehog_scan:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@v3.95.0
        with:
          extra_args: --only-verified
